### ISSUE TITLE
Use individual lodash packages

### ISSUE THREAD

**Issue by flaviusone** [skidding/react-data-fetch#12]
As the title suggests we can shave off some useless lodash code that can get into a final app bundle. 

It would be even better if we could get rid of it at all.

![image](https://cloud.githubusercontent.com/assets/1254386/23485173/fa9c8d2a-fee2-11e6-9183-cacc7ee2e2e3.png)

**Comment by skidding** [comment]
![do it](https://cloud.githubusercontent.com/assets/250750/23496742/6e5bdc8a-ff28-11e6-8a5a-397dff055ae8.gif)

**Comment by RadValentin** [comment]
@flavius-tirnacop-hs Mind if I tackle this one? Could be a quick win for us.

**Comment by RadValentin** [comment]
@flaviusone Mind if I tackle this one? Could be a quick win for us.

**Comment by flavius-tirnacop-hs** [comment]
> @flaviusone Mind if I tackle this one? Could be a quick win for us.

Sure!
